services:
  backend:
    container_name: glitch-backend
    build:
      context: .
      dockerfile: .docker/backend.local.dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/glitchr
      - APP_NAME=glitch:local
      - HTTP_PORT=8080
    volumes:
      - ./cmd/:/app/cmd/
      - ./internal/:/app/internal/
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
  
  
#   db:    
#     image: postgres:15
#     container_name: postgres_db
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: glitchr
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: password
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     logging:
#       driver: "none"
  
#   redis:
#     image: redis:7.4.2
#     container_name: redis
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     logging:
#       driver: "none"

# volumes:
#   postgres_data:
#   redis_data: