{{- range $secretName, $secretData := .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Chart.Name }}-{{ $secretName }}-sk
  namespace: {{ $.Values.namespace | default $.Release.Namespace | quote }}
type: Opaque
data:
{{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
---
{{- end }}
