basePath: /
definitions:
  server.AuthResponse:
    properties:
      error: {}
      message:
        type: string
    type: object
  server.ConfirmSignupRequest:
    properties:
      email:
        type: string
      otp:
        type: string
    required:
    - email
    - otp
    type: object
  server.HealthResponse:
    properties:
      status:
        $ref: '#/definitions/server.Status'
    type: object
  server.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  server.Profile:
    properties:
      email:
        type: string
      name:
        type: string
      sub:
        type: string
    type: object
  server.ProfileResponse:
    properties:
      data:
        $ref: '#/definitions/server.Profile'
      error: {}
      message:
        type: string
    type: object
  server.SignUpRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  server.Status:
    enum:
    - UP
    - DOWN
    type: string
    x-enum-varnames:
    - StatusUp
    - StatusDown
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: subrotokumar@outlook.in
    name: Subroto Kumar
    url: http://github.com/subrotokumar/glitchr
  description: API Dccumentation for Glitch Backend.
  license:
    name: Apache 2.0
  title: Glitchr
  version: "1.0"
paths:
  /auth/confirm-signup:
    post:
      consumes:
      - application/json
      description: Confirm a user's signup using OTP
      parameters:
      - description: Confirm signup payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/server.ConfirmSignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.AuthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.AuthResponse'
      summary: Confirm signup
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and set access/refresh cookies
      parameters:
      - description: Login payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/server.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.AuthResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.AuthResponse'
      summary: Login user
      tags:
      - auth
  /auth/profile:
    post:
      consumes:
      - application/json
      description: Get Profile Detail
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.ProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ProfileResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ProfileResponse'
      summary: Profile
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh access token using refresh token cookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.AuthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.AuthResponse'
      summary: Refresh access token
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Sign up payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/server.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.AuthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.AuthResponse'
      summary: Sign up a new user
      tags:
      - auth
  /health/liveness:
    get:
      description: Indicates whether the application process is alive
      produces:
      - application/json
      responses:
        "200":
          description: Service is alive
          schema:
            $ref: '#/definitions/server.HealthResponse'
      summary: Liveness probe
      tags:
      - health
  /health/readiness:
    get:
      description: Indicates whether the application is ready to receive traffic
      produces:
      - application/json
      responses:
        "200":
          description: Service is ready or not
          schema:
            $ref: '#/definitions/server.HealthResponse'
      summary: Readiness probe
      tags:
      - health
swagger: "2.0"
